services:
  app:
    container_name: community_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - MQ_URL=amqp://guest:guest@lab3_mq:5672/core
      - JWT_SECRET_ACCESS_KEY=esto es una key re segura
    networks:
      - lab3_shared_network

  outbox_relay:
    container_name: community_outbox_relay
    build:
      context: ../outbox-relay
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - MQ_URL=amqp://guest:guest@lab3_mq:5672/core
      - SERVICE_NAME=community
      - MQ_VHOST=core
      - POLL_INTERVAL_MS=500
    networks:
      - lab3_shared_network

networks:
  lab3_shared_network:
    external: true
