services:
  app:
    container_name: community_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - MQ_URL=${MQ_URL}
    networks:
      - lab3_shared_network

  outbox_relay:
    container_name: community_outbox_relay
    build:
      context: ../outbox-relay
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - MQ_URL=${MQ_URL}
      - SERVICE_NAME=${APP_NAME}
      - MQ_VHOST=${MQ_VHOST}
      - POLL_INTERVAL_MS=${POLL_INTERVAL_MS}
    networks:
      - lab3_shared_network

networks:
  lab3_shared_network:
    external: true
