CREATE TABLE PUBLIC."COMMUNITY" (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    RULES TEXT,
    BANNER_URL VARCHAR(255),
    PROFILE_URL VARCHAR(255),
    CREATED_BY UUID NOT NULL,
    ACTIVE BOOLEAN DEFAULT true,
    CREATED_AT TIMESTAMP NOT NULL
);
    
CREATE TABLE PUBLIC."USER" (
    ID UUID PRIMARY KEY
);

CREATE TABLE PUBLIC."COMMUNITY_MEMBER" (
    COMMUNITY_ID UUID NOT NULL REFERENCES PUBLIC."COMMUNITY"(ID) ON DELETE CASCADE,
    USER_ID UUID NOT NULL REFERENCES PUBLIC."USER"(ID) ON DELETE CASCADE,
    ROLE VARCHAR(50) DEFAULT 'MEMBER' CHECK(ROLE IN ('MEMBER', 'MODERATOR')),
    JOINED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (COMMUNITY_ID, USER_ID)
);

CREATE TABLE PUBLIC."OUTBOX_EVENT" (
	ID UUID PRIMARY KEY,
	AGGREGATE_TYPE VARCHAR NOT NULL CHECK(AGGREGATE_TYPE IN (
			'COMMUNITY_CREATED',  
			'COMMUNITY_UPDATED',
            'MEMBER_LEFT',
            'MEMBER_JOINED'
		)
	),
	AGGREGATE_ID UUID NOT NULL,
	TYPE VARCHAR NOT NULL CHECK(TYPE IN ('COMMUNITY', 'COMMUNITY_MEMBER')),
	PAYLOAD JSONB NOT NULL,
	STATUS VARCHAR NOT NULL CHECK(STATUS IN ('PENDING', 'COMPLETE', 'FAIL')),
	CREATED_AT TIMESTAMPTZ NOT NULL,
	UPDATED_AT TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_community_outbox_pending 
ON PUBLIC."OUTBOX_EVENT" (CREATED_AT ASC) 
WHERE STATUS = 'PENDING';

CREATE INDEX idx_community_member_user ON PUBLIC."COMMUNITY_MEMBER"(USER_ID);
CREATE INDEX idx_community_member_moderators ON PUBLIC."COMMUNITY_MEMBER"(COMMUNITY_ID) WHERE ROLE = 'MODERATOR';